ionic-team/ionic-app-scripts

src/watch.ts

This PR should prevent the memory overruns that we have seen from rollup. The code ensures that we are running only watch task at a time by using the returned promises.  It also uses a single entry queue so that we only run one additional watch task on previous task completion.

fix(watch): Ensure that watch tasks are throttled to run one at a time per watcher.

---

config/copy.config.js

refering to this:  https://github.com/driftyco/ionic/issues/8256

fixed missing service worker copy

---

src/util.ts

When an exception is a plain string nothing is printed. This change will log string exceptions, and will also only log stack if it exists.
In my case the build was not correctly clearing the .tmp folder and throwing a string error that looked like: "tmpDir error: Error: ENOTEMPTY: directory not empty, rmdir"

fix(util): Fix logging of string exceptions

---

config/rollup.config.js
package.json

This is needed for libraries which use built in node methods such as PouchDB. These plugins have no effect on libs which do not use these methods. Without this added a user will have to add these plugins themselves which is not ideal in my opinion.

fix(rollup): add globals and defaults plugins

---

src/copy.ts
src/ngc.ts
src/sass.ts
src/spec/util.spec.ts

In various places fillConfigDefaults is called from the watcher with `{}` instead of `null`. The method then applies default configs to the empty object and therefore returns basically the default values instead of the user specified configs. fillConfigDefaults has to be called with `null` in these cases.
I also added some unit tests for fillConfigDefaults to verify that empty object ignores all user configs and null loads them.
-
-
-
**Fixes**: #
fillConfigDefaults is now called with null instead of empty object during watch. Verified that it works for the sass task in my project. My specified sass config overrides are now also used by watch.
Because watch is called in various places with an empty object, fillConfigDefaults will not load user specified defaults and just apply the …

Make sure all watcher updates respect user specific configs

---

src/copy.ts

Copy no longer overwrites a directory when it is written too. This allows the use case of someone setting up a custom copy.config that copies two seperate src directories to the same destination directory.
- add the [clobber](https://github.com/jprichardson/node-fs-extra#copy) option and set it to false
**Fixes**: #78

fix(copy): fixes #78

---

package.json

When checking if there was a nightly available on npm, I spotted the following `homepage` property when running `npm view @ionic/app-scripts`:
```js
homepage: 'http://http//ionicframework.com/'
```
- Fix the typo in `package.json`

fix(package): homepage typo

---

config/watch.config.js

When making a change to the index.html file it now triggers a change and gets copied over to www/index.html as it should.
- remove the ignore

fix(watch): index.html changes watched and updated

---

.gitignore
src/util/config.ts

If the required config errors, it says "Config not found" which is misleading.

fix(config): clarify missing vs erroring user config

---

src/copy.ts

Fixes issue #305 - resolves the issue of getting a 'TypeError - can't find "indexOf" of undefined' while building the project.
- Check err object to see if it has a "message" parameter before calling "indexOf" on that parameter. 
**Fixes**: #305 
A "TypeError - can't find "indexOf" of undefined" was being thrown in copySrcToDest function when a copy error was detected and its message was interpreted.

Fixed nullpointer in copy.ts 

---

src/index.ts

Not quite sure if `buildUpdate` from build is required, but I assume the `watch`  `buildUpdate` can be used instead as it also offers denouncing. Although in the watch buildUpdate `js`  files are not handled but there is another `PR` for this https://github.com/driftyco/ionic-app-scripts/pull/375.
Would be nice if the tasks are wrapped in a module thus you can export the whole module add and consume them something like;
```js
const ionicScripts = require("@ionic/app-scripts");
ionicScripts.watch.buildUpdate(...);
```
or internally
```ts
import { watch } from "./watch";
watch.buildUpdate(...);
import { build } from "./build";
build.buildUpdate(...);
build.runBuildUpdate(...);
```
The above will also solve the issue that in different module/files the method names are called the same.
- …

bugfix(buildUpdate): export BuildUpdate from watch rather than build

---

src/watch.ts

When you link npm module you still need to listen for changes on them. The file extension in would mainly be "js" which at the time being is not handled.
- Support JS file changes
Issue: #380

feat(run-build-update): handle linked npm modules

---

README.md

Readme still shows the old NPM scripts, although both the [changelog](https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md) and [blog post](http://blog.ionic.io/improvements-to-ionic-build-process/) recommend using the new ones.

chore(readme): update npm scripts

---

config/copy.config.js
config/sass.config.js

This fixes the roboto and noto-sans fonts not getting included. The copy task did not copy over the fonts before and instead just copied over ionicons. It now copies over fonts and ionicons. This also changes the sass config to make sure it looks in the right directory.
- Change copy.config to pull in all fonts instead of just ionicons
- Change sass.config to look in the right directory
**Fixes**: #73

fix(): fixes issue #73

---

src/dev-server/http-server.ts

Proxies list of ionic.config.json not loading
Wrong parameter in Logger.info(), in setupProxies function stops proxies loading
**Fixes**: #346

fix(proxies): Proxies list of ionic.config.json not loading

---

config/webpack.config.js

Fixes packages that are linked via `npm link`. See https://github.com/angular/angular-cli/pull/2291 for more details.
- Added a `resolve.modules` property to webpack config to support linked modules.

fix(webpack): resolve modules to rootDir

---

src/cleancss.ts

CleanCss has several Options that users can provide their own options
- Add options to the cleanCss interface
- Add pass the config.options when initializing the cleanCss

feat(options): allow users to pass their own cleanCss Options

---

package.json

add typings to be able to consume it like an API
example
```ts
import { sass } from "@ionic/app-scripts";
```

chore(packages): add typings to be able to consume it like an API

---

src/spec/config.spec.ts
src/util/config.ts
src/webpack.ts

Refactor replacePathVars to support Arrays, Objects and Strings
**Fixes**: #238

feat(replacePathVars): support interpolation of objects and arrays

---

src/dev-server/http-server.ts
src/dev-server/serve-config.ts
src/serve.ts

There was a regression in 2.1.8 when we moved `run` and `emulate` serve responsiblity away from cli to app-scripts. This adds the logic within app-scripts to serve cordova plugins through express to emulators or devices.
This does add one flag to the `serve` command that indicates when the serve command should be accessed from a native device. This is named `--iscordovaserve`
**Fixes**: #467

Livereload run fix

---

src/dev-server/live-reload.ts

When the dev server listens on 0.0.0.0, it injects a live reload script that looks like this: `<script src="//0.0.0.0:35729/livereload.js?snipver=1" async="" defer=""></script>`. This PR replaces 0.0.0.0 with localhost in this case.

Use localhost instead of 0.0.0.0 when injecting live reload script

---

config/sass.config.js
config/watch.config.js

ionic-app-scripts does not compile nor watch Sass indented files
- Change sass.config.includeFiles and watch.config regular expressions to match *.sass and *.scss files

feat(sass): enable Sass indented files compilation

---

src/template.ts

Fixes error with templateUpdate and multiple js files on same path.
replaceExistingJsTemplate return null if no template is found and then it sets javascriptFile.content = null making it fail the next time it tries to build
still fails if saving a template twice without any changes but im not sure it should even reach this part if the file has no changes? 
-
-
-
**Fixes**: #

Fixes error with templateUpdate and multiple js files on same path

---

README.md

In the 0.0.47 release the `ionic_source_map_type` config was renamed to `ionic_source_map_type`. This commit update the example package.json config to use the new name.

chore(README): update example package.json config

---

README.md

This change updates the information provided about the new setting for `prod` builds starting at version `0.0.47`, specifically that all tasks produce `dev` builds unless you use the `--prod` argument.

Update ReadMe.md, updating prod/dev build info

---

src/dev-server/notification-server.ts

Fixes an issue where a rebuild is started during `ionic serve` from a file change, when no browsers are loaded with the app running.
- Guard against an undefined `wsServer`
**Fixes**: #590 #599 #535

Fix exception when no ws clients connected during rebuild

---

src/aot/aot-compiler.ts

Preserves custom decorators to support libraries such as ngrx/effects.
See [here](https://github.com/driftyco/ionic-app-scripts/issues/545) for a transcript of the issue.

Temporary fix to keep custom decorators when aot compiling

---

src/aot/utils.ts

I haven't been able to get NGC to kick in using different flags as mentioned at d53f25f, this typo might be the cause of the issue.
A typo that was pushed to the repo on [5d82829](https://github.com/driftyco/ionic-app-scripts/commit/0594803ca5b2136e666c3007540491ad2e72f06c#diff-29ed0d301ecfa6169cc5c75c1e54a6e4R99)

Fix(typo): Properly appends

---

config/copy.config.js

Do not merge until https://github.com/driftyco/ionic2-app-base/pull/118 is merged. This adds the copy config entry to copy` sw-toolbox.js` to build.
- add a copy config entry

chore(config): add swtoolbox to copy

---

src/util/config.ts

This allows custom configs to run as a function so that logic can be executed and determined at runtime.
- Adds a simple logic gate to detect if config that is required returns a function. If so call it to retrieve assignable object.
**Fixes**: #666

Allow user config to be function

---

config/sass.config.js

Removes `ionicons` from the `includePaths` to avoid getting CSS that we don't want.
------------------------------------------------------------------------------------
**IMPORTANT:**
This is dependent on driftyco/ionic#10115. If you try to use this Sass config without that PR it will throw errors that it can't find `ionicons-icons` or `ionicons-variables`.

chore(ionicons): remove the import of ionicons css

---

src/uglifyjs.ts

inSourceMap not being used during uglification.
- Pass the inSourceMap setting to uglifyjs.minify
**Fixes**: #613

Make sure the inSourceMap gets passed to uglifyjs

---

src/worker-client.ts

In my cleancss.config.js and uglifyjs.config.js, I am dependent on npm args. However the worker-client is being spawned as another process, which is causing the args and npm config argv not to be passed.
- pass the argv
**Fixes**: #463

feat(createWorker): pass argv and config_argv to spawned processes

---

README.md

Fix a small typo in the README.

docs(README): fix typo in task description

---

src/build.ts

Fix test if linting should trigger on file change. It was checking on the event being `ch` instead of `change`.
**Fixes**: #718

fix(build): fix test if linting should trigger on file change

---

src/babili.ts
src/minify.ts
src/util/helpers.ts
src/util/source-maps.ts

The code base was not yet ready for TypeScript 2.1, spitting out some type errors when running `npm run build`.
This patch fixes some type annotations to be compatible with both TypeScript 2.0 and 2.1.
This is one step in fixing #197 (and #649 where support for TypeScript 2.1 seems to be a pre-condition).

chore(build): fix build issues with typescript 2.1

---

src/serve.ts
src/util/network.ts

Up to now only the logger port was dynamically increased if another app
is running already. This meant that manually specifying port arguments
for server and live reload was needed when directly using the
`ionic-app-scripts server` command. The `ionic` CLI command does
already take care of this.
This patch ensures all the ports are chosen dynamically, so it's now
possible to run two applications without any manual intervention.
**Fixes**: #694

fix(serve): assign all ports dynamically

---

src/serve.spec.ts

PR #727 introduced an internal API change that triggered failing specs.
This PR adapts the tests, so they run properly again.

test(server): adapt server specs to new dynamic port selection

---

src/util/config.ts

ENV_READ_CONFIG_JSON constant was being set wrong by resolving --readConfigJson argument as path instead of boolean.
That was causing if statement in line 56 of http-server.ts being always false, so the proxies could not load.
**Fixes**: #759

fix(readConfigJson): Setting readConfigJson constant wrong

---

src/babili.spec.ts
src/babili.ts
src/transpile.ts
src/uglifyjs.spec.ts
src/uglifyjs.ts

This PR adds functionality to minify all bundles that get created, not just the main bundle. It also adds new tests tests around this functionality.
- Modify uglify function to minify all bundles that get created
- Modify transpile function to transpile all bundles that get created
- Modify babili function to minify all bundles that get created
- Improve error handling

feat(minification): code-split bundles will be minified

---

src/deep-linking/util.ts
src/upgrade-scripts/add-default-ngmodules.spec.ts
src/upgrade-scripts/add-default-ngmodules.ts

Tmp stashing

---

bin/ionic-app-scripts.js

Fixes `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` errors when building with `--prod` flag.  
- adds the `--max-_old_space_size=2048` flag to the `ionic-app-scripts.js` to increase the heap size
**Fixes**: #766

fix out of memory errors

---

config/uglifyjs.config.js
src/babili.spec.ts
src/babili.ts
src/optimization.spec.ts
src/optimization.ts
src/uglifyjs.spec.ts
src/uglifyjs.ts

Uglify fixes

---

README.md

Add badges in readme. This is especially useful to know which version is the latest, rather than having to go to the changelog everytime.

docs(README): add badges for `npm` and `circleci`

---

bin/ionic-app-scripts.js

Linux only accept one argument in a shebang, so everything after the
/usr/bin/env is seen as one argument.
For setting this node option, see
https://github.com/npm/npm/issues/12238
- Remove shebang argument
**Fixes**: #838

Fix bash script on linux

---

src/serve.ts
src/util/open.ts

Browser open doesn't work on unix system because of a reference to a missing external script (vendor/xdg-open).
This is a quick fix what uses xdg-open installed on the system. Works on Ubuntu system and probably in a lot of Linux distribution because xdg-open is quite popular.
I also added a warning message if the system command throws an error.
-
-
-
**Fixes**: #425

Using system wide xdg-open to open browser, fixes #425

---

src/generators/util.spec.ts

Resolves an issue where some tests were failing sometimes (most likely because of a race condition). This was because the test was sync but the logic is async.
- Improve broken tests
- Some cleanup

test(generators): improve failure path tests

---

src/webpack.ts

Prior to this patch, the script would only raise "internal" errors raised by webpack and skip "compilation" errors that could be caused by faulty config or source code. This is contrary
to what webpack suggests in terms of error handling[1].
This patch makes it so that any compilation errors will cause ionic to also abort the build, while any compilation warnings will log a warning through ionic's Logger.
[1] https://webpack.js.org/api/node/#error-handling

Propagate errors from webpack stats

---

src/sass.ts

POstCss has a number of plugins, and it would be cool that user can provide their own plugin through config
```js
postCssPlugins: [
require('precss') 
]
```

feat(sass): add option to pass addition postcss plugins

---

src/build.spec.ts
src/build.ts
src/transpile.ts

While typescript support `extends` of another tsconfig, a limitation in `validateRequiredFilesExist` method doesn't as it's reading the file using `fs`, rather than `getTsConfig` which is a wrapper of the `TypeScript API`, 
- Impalement `getTsConfigAsync`  method
- In `validateRequiredFilesExist` use it rather than `readFileAsync` for the `tsconfig.json`
Note: I cannot run Unit Tests
**Fixes**: #745

fix(build): fix `extends` in `ts-config.json`

---

src/generators/util.ts

ES2015 imports should always have unix style paths, previously on windows our code would insert an import that used a windows style path.
- use `toUnixPath` to transform our generated paths for imports
**Fixes**: https://github.com/driftyco/ionic-cli/issues/2150

Gen windows fix

---

src/dev-client/sass/_diagnostics.scss

Diagnostics data is errors in English and should show from left to right, even when developing rtl apps, especially as it is not a part of the core framework
- Add direction for ` #ion-diagnostics`

fix(diagnostics): change direction to always be ltr

---

package.json

when I run script:
npm install --save @ionic/app-scripts
the cmd log:
https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node 
HTTP error 404 Not Found
And I see https://github.com/sass/node-sass/releases, v4.5.0/win32-x64-57 no longer exists!
So can I modify  node-sass version to work this out？
v4.5.0/win32-x64-57 is no longer exists!
- "node-sass" : "4.5.0"
+ "node-sass" : "4.5.3" 
**Fixes**: #
I think it's should be able to fix

Update package.json to fix v4.5.0/win32-x64-57 ( HTTP error 404 Not Found) error

---

lab/static/js/lab.js

It seems that, when you start ionic in labs mode with --lab, you do not have the possibility to pass config options by extending the url with ?ionicsomesetting=1, which you would normally get in your app with config.get('somesetting').
this patch passes the parameters on to the individual iframes in lab mode.
**Fixes**: #2431

patch for passing params from lab to iframes

---

CHANGELOG.md
lab/index.html
scripts/create-github-release.js
src/aot/aot-compiler.ts
src/build.ts

I found some "old" driftyco links and renamed them to ionic-team

refacator(): rename driftyco references to ionic-team

---

src/watch.ts

`.sass` files are built but not watched, it means we need to relaunch `serve` each time a sass file is changed.
- Watch `*.sass` files on top of `*.scss` files

fix(sass): fix .sass files not being watched

---

scripts/publish-nightly.js

feat(scripts): push npm build to arbitrary tag

---

src/sass.ts

If `ionic-app-scripts sass` is run it currently fails even if a sass file is provided directly using sassConfig.file. The failure happens because a bundle is triggered which is not actually necessary if sassConfig.file is specified. This PR simply disables the bundling if sassConfig.file is set.
- Do not start bundle if a sass file is chosen in config
- replace path vars for sassConfig.file
**Fixes**: #972 (partially)

Make sass command work if a sassConfig.file is provided

---

README.md

The config parameter is named `ionic_enable_lint`, not `enable_lint`

Fix config param naming

---

src/dev-server/http-server.ts
src/dev-server/injector.ts

Assuming you wish to use the path location strategy in the Ionic app
```
locationStrategy: 'path'
```
and are running `ionic serve`.
Currently you can load your index page and navigate around fine. The path in the browser is updated to `/about` for example. However if you refresh this `/about` page, you get a 404 because that path does not exist.
Added a catchall route so that 404 will get sent to the index page and the Ionic deeplinker can handle routing to the `about` segment.

Support path based routing in dev-server

---

src/generators/util.ts

By default, `generate` will make a NgModule by default, Since we do not ship lazy loading by default, we should not generate this right now. 
-  set`includeNgModule` to false for now.

fix(generators): no module by default

---

.npmrc
src/generators.ts
src/generators/util.spec.ts
src/generators/util.ts

Closes https://github.com/ionic-team/ionic-cli/issues/2519
Fixes an oversight when generating tabs. 
Generating tab will attempt to modify a root ngModule with additional components.
This will handle situations when a page/tab is not lazyloaded.
- Handle variable reference as a Component and String
- Make sure component is imported properly 
**Fixes**: https://github.com/ionic-team/ionic-cli/issues/2519

fix(generators): handle no ngModule in tabs

---

src/util/config.ts

Fixes the "no such file or directory" error while generating pipes.
Problem was the uppercase PIPES dir in the path for generating the pipes.module.ts file
**Fixes**: [#2621](https://github.com/ionic-team/ionic-cli/issues/2621)

change default pipe dir name from PIPES to pipes

---

src/index.ts

This resolves the issue that certain tasks that only run a part of the build chain no longer worked (see issue #701) 
I moved the call to setContext to the run method, so it is executed for all commands.

Fix for #701

---

src/dev-server/http-server.ts
src/util/ionic-project.ts

This allows cookies to be forwarded correctly when using a proxy
to an HTTPS URL.
Related:
* ionic-team/ionic-app-scripts#454
* ionic-team/ionic-cli#415
This resolves an issue where cookies are not forwarded when a proxy to an HTTPS URL is used. This has been discussed in the past, but a corresponding PR has been closed without any explanation (alongside the ticket).
I'm not really in knowledgeable in this area, so if this change is problematic, we should at least clarify why and how it could be solved otherwise. 
- Add a `cookieRewrite` option to the proxy configuration which is passed to proxy-middleware.
**Fixes**:
* ionic-team/ionic-cli#415
* Possibly ionic-team/ionic-app-scripts#454 ?

Added a cokieRewrite option which is passed to proxy-middleware.

---

src/template.ts

Fix template loading when html element attribute is object and string value contain antislash
-
-
-
**Fixes**: #

Fix template loading

---

package.json

This  PR upgrades node-sass to support Node.js 9.0
**Fixes**: #1303

fix(node-sass): Node 9.0 support

---

src/uglifyjs.ts

remove unused `readFileAsync` during uglify

perf(uglifyjs): remove unused `readFileAsync` during uglify

---

src/dev-server/http-server.ts
src/dev-server/serve-config.ts

Native plugins do not work with the live server for users using Cordova 8. The current path in the config is valid for Cordova < 8. However, if you install ionic today following the directions on the site you get Cordova 8 by default and therefore the live server can't find cordova. Anything attempting to do native operations results in the error message: `Cordova is not available. Make sure to include cordova.js or run in a device/simulator (running in emulator)`
This has been broken since at least this [11/26/2016 Stack Overflow post](https://stackoverflow.com/questions/40815183/ionic-2-cordova-is-not-available-make-sure-to-include-cordova-js-or-run-in-a-d)
To maintain backward compatibility for Cordova 7 I've changed the platform path variables to arrays of strings and included both …

fix(live-server): update android platform path

---

package.json

"ionic start" build fail with node 10 on windows
- Updated node-sass dependency from 4.7.2 to 4.9.0 
**Fixes**: #

Update node-sass dependency

---

README.md
config/webpack.config.js
package.json

Add support for using process.env.MY_VAR syntax in app code
Allow for customization of bundled application code based on environment configuration files and environment variables. This enables better support for customization using CI/CD tools.
By adding the [DotEnv webpack plugin](https://github.com/mrsteele/dotenv-webpack) to the webpack config users can now add Node style `process.env.MY_VAR` style syntax directly into their typescript and when the application is bundled it'll be replaced with the following order of precedence.
* If the variable exists in the process environment it will be that value. 
* If the variable is not defined in the process environment it will be read from a `.env.dev` file for dev builds or `.env.prod` file for prod builds which are located in the root of the …

feature(environment configuration)

---

src/sass.ts

This removes following warning:
Remove warning: Without `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
`from: the input file name (most runners set it automatically).`
Source: https://github.com/postcss/postcss
Fixes #1359 #13763
https://github.com/ionic-team/ionic-app-scripts/issues/1359
https://github.com/ionic-team/ionic/issues/13763
This removes the PostCSS warning, which is resulting in an error in our automated builds.
- Just add `from` field with an undefined value, as mentioned in the warning.
**Fixes**:  #1359 #13763

Remove PostCSS warning

---

bin/ion-dev.js

When using an https (and wss) reverse proxy for the browser platform, the hardcoded ws protocol WebSocket connection gives a Mixed Content error.
- attempt to connect to the WebSocket with wss when the page is on https
I know there is some work being done towards better support for https in development environments (see [https://github.com/ionic-team/ionic/issues/1686]()) but I'm wondering if this small change would be acceptable as a stop-gap?

use wss: protocol for secure websocket when page is using https:

---

package.json

The version 3.8.1 of Webpack doesn't have the fixe [#6407](https://github.com/webpack/webpack/issues/6407) which fix the build in AoT for multilingual application.
- Update the version of Webpack to 3.12.0

Update Webpack to 3.12.0 to resolve AoT build issue

---

package.json

This should fix the security warnings `npm audit` reports (related to the `hoek` library).

Bump node-sass to 4.9.3 to fix security warnings

---

package.json

in node-sass 4.10 required version of package request was updated from v2.79.0 to v2.88.0:
- vulnerable package tunnel-agent v0.4.3 updated to v0.6.0 (https://github.com/request/request/commit/fa48e67578a3c43f83c9e4e9339440e8dbbcf6f5)
- vulnerable package hoek removed (https://github.com/request/request/commit/a6741d415aba31cd01e9c4544c96f84ea6ed11e3)

chore(deps): bump node-sass to 4.10.0 to fix security warnings

---

README.md

Reverts ionic-team/ionic-app-scripts#1508

Revert "docs(readme): update readme with nightly build instructions"

---

src/template.ts

HTML template of components is not updated by ionic serve after saving the file.
When a module is shared among multiple modules, e.g., a components module, the component template is present in multiple bundle files, so the template should be replaced in all bundle files.
Instead of only replacing the template in the first matching bundle file, replace it in all matched bundle files. So removing the `break` fixes this.
**Fixes**: #1132

Fix for 1132: Component HTML template not updated when saved

---

src/aot/aot-compiler.ts
src/aot/compiler-host-factory.ts
src/aot/compiler-host.ts
src/transpile.ts

When running `ionic serve` it often happens that the transpiled files become out of date. After making a change to one of the TypeScript source files, ionic serve runs, but when looking at the built JavaScript files, the new code is not present. I found that the app-scripts build process kept two file caches. One in the app-script context and one in the so called InMemoryCompilerHost. The first was updated when files changed, but the latter wasn't. The InMemoryCompilerHost cache is in my opinion superfluous, because it got injected a HybridFileSystem, which nicely uses the app-scripts context fileCache. My solution is to remove the cache from the InMemoryCompilerHost, rename the InMemoryCompilerHost to FileSystemCompilerHost and let the injected HybridFileSystem handle the caching. This …

Fix: Ionic serve files out of date
