ionic-team/ionic-app-scripts

- src/spec/util.spec.ts
- src/util.ts
> Avoid mutation of same rollupconfig instance on watch

- src/bundle.ts
> fix(rollup): output to the right destination on update

- src/bundle.ts
> chore(bundle): add memory usage debug log

- config/closure.config.js
Changed config value to be a path to java executable
> feature(closure): closure config value is now a path to java executable

- src/build.ts
> fix(): fix ts errors

- src/index.ts
There are some missing exports that are needed if you do a custom watch config
- Add templateUpdate and fullBuildUpdate as exports
**Fixes**: #295
> feat(exports): add templateUpdate and fullBuildUpdate

- src/webpack/ionic-environment-plugin.ts
> fix(webpack): typo in import, close #326

- README.md
> doc(available task): change tsc to transpile

- src/dev-server/notification-server.ts
If there are multiple pages pointed at the notification server and a build occurs it currently only causes a reload on the last connection.  This is very noticeable when viewing '--lab' page. This update broadcasts build updates to all clients.
**Fixes**: #461
> fix(livereload): on project build all pages connected should reload.

- config/watch.config.js
Add e2e tests files to ignore list in watch.config
> Add e2e tests files to ignore list

- config/sass.config.js
Reverts driftyco/ionic-app-scripts#669
> Revert "chore(ionicons): remove the import of ionicons css"

- config/optimization.config.js
- src/optimization.spec.ts
- src/optimization.ts
- src/optimization/treeshake.spec.ts
- src/optimization/treeshake.ts
> Provider shake

- package.json
- src/dev-server/bonjour.ts
- src/dev-server/serve-config.ts
- src/serve.spec.ts
- src/serve.ts
> feat(bonjour): adds service autodiscovery

- package.json
- src/dev-server/bonjour.ts
- src/dev-server/serve-config.ts
- src/serve.spec.ts
- src/serve.ts
> fix(bonjour): updates dependency + better error handling

- CHANGELOG.md
> fix(changelog): typo in word

- bin/ion-dev.js
> fix(devapp): do not enable shake

- CHANGELOG.md
> missing cordova command and wrong paramter passed

- src/core/inject-script.spec.ts
- src/core/inject-scripts.ts
Do not use greedy regex, it may leave invalid html
Use non greedy regex
-
-
-
**Fixes**: #1220
> Do not use greedy regex when replacing index.html

- src/logger/logger-typescript.ts
Fixes some random build errors.
Im not shure which repo caused this problems but this line fixed them.
**Fixes**: #2889
> fix(2889): fix build error with --prod

- README.md
- Updates README with instructions on how to run a nightly build
- Adds extra step to ensure changes are in master for release builds
- Add nightly build instructions
- Update release build instructions
**Fixes**: #
> docs(readme): update readme with nightly build instructions
